<?php

/**
 * @file
 * TODO
 */

/**
 * Implements hook_menu().
 */
function secure_notes_menu() {
  $items = array();
  $items['admin/config/content/secure-notes'] = array(
    'title' => 'Secure Notes Settings',
    'description' => 'Administer Secure Notes Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secure_notes_admin_settings_form'),
    'access arguments' => array('manage secure notes settings'),
    'file' => 'secure_notes.admin.inc',
  );
  $items['secure-notes/add/%'] = array(
    'title' => 'Create Secure Note',
    'description' => 'Create a secure note',
    'page callback' => 'secure_notes_render_add_form',
    'page arguments' => array(2),
    'access callback' => 'secure_notes_add_token_valid',
    'access arguments' => array(2),
    'file' => 'secure_notes.pages.inc',
  );
  $items['secure-notes/view/%'] = array(
    'title' => 'View Secure Note',
    'description' => 'View a secure note',
    'type' => MENU_CALLBACK,
    'page callback' => 'secure_notes_render_node_view',
    'page arguments' => array(2),
    'access callback' => 'secure_notes_view_token_valid',
    'access arguments' => array(2),
    'file' => 'secure_notes.pages.inc',
  );
  $items['admin/content/secure-notes/invite/add'] = array(
    'title' => t('Generate Secure Note Add Link'),
    'description' => t('Generate a one time use link for the creation of a note.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secure_notes_add_link_invite'),
    'access arguments' => array('secure notes invite add'),
    'file' => 'secure_notes.pages.inc',
  );
  $items['node/%/secure-notes/invite'] = array(
    'title' => t('Secure Note Invitation'),
    'type' => MENU_LOCAL_TASK,
    'description' => t('Generate a one time use link that can be used to view this node.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secure_notes_view_link_invite'),
    'access callback' => 'secure_notes_node_invite_access',
    'access arguments' => array(1, 'secure notes invite view'),
    'file' => 'secure_notes.pages.inc',
  );
  /*
  $items['admin/content/secure-notes/email'] = array(
    'title' => t('Send Secure Note Email'),
    'description' => t('Generate a one time use link for the creation of a note.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secure_notes_generate_link'),
    'access arguments' => array('generate secure notes links'),
    'file' => 'secure_notes.pages.inc',
  );
  */
  return $items;
}

/**
 * Implements hook_permission().
 */
function secure_notes_permission() {
  return array(
    'secure notes invite add' => array(
      'description' => t('Create link invitations to allow the creation of new secure notes.'),
      'title' => t('Generate secure note add invitations'),
      'restrict access' => TRUE,
    ),
    'secure notes invite view' => array(
      'description' => t('Create link invitations to allow the viewing of secure notes.'),
      'title' => t('Generate secure note view invitations'),
      'restrict access' => TRUE,
    ),
    'secure notes node view' => array(
      'title' => t('View secure notes'),
      'description' => t('Secure notes need to be private to be secure. Allows access to secure note content.'),
      'restrict access' => TRUE,
    ),
  );
}

/*
 * Implementation of hook_help()
 */
function secure_notes_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#secure-notes':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Secure notes module was designed to solve the problem of transfering sensitive data between people. While there are many good solutons for this (PGP, SSH, TrueCrypt, etc) it is often the case that one or more of the parties are non-technical or unable to install new software. In this case, it is possible to allow transfer of this data by storing it in Drupal.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('Secure notes allows any content type to be made into a secure drop point. To authorize a user to create a secure not, generate a token and email it to them. This is very similar to the way users can reset a password. The one time link will allow them to create a node even though they do not have access to the site in any other way.') . '</p>';
      $output .= '<p>' . t('If you need to send a secure not to someone, generate a similar one-time use access link and they can then view a specified piece of content, once and only once.') . '</p>';
  }
  return $output;
}

/**
 * TODO
 */
function secure_notes_add_token_valid($token) {
  $result = db_select('secure_notes_create', 'snc')
    ->fields('snc', array('expires', 'type'))
    ->condition('token', $token, '=')
    ->execute()
    ->fetchObject();
  $access = ($result && (int) $result->expires > REQUEST_TIME && secure_notes_type_allowed($result->type));
  if (!$access) {
    drupal_set_message(t('The token you supplied is either invalid, has expired, or already been used. Please check that the url matches the one that was given to you.'), 'error');
  }
  return $access;
}

/**
 * TODO
 */
function secure_notes_view_token_valid($token) {
  $result = db_select('secure_notes_view', 'snv')
    ->fields('snv', array('expires'))
    ->condition('token', $token, '=')
    ->execute()
    ->fetchObject();
  $access = $result && (int) $result->expires > REQUEST_TIME;
  if (!$access) {
    drupal_set_message(t('The token you supplied is either invalid, has expired, or already been used. Please check that the url matches the one that was given to you.'), 'error');
  }
  return $access;
}

/**
 *TODO
 */
function secure_notes_node_invite_access($nid, $perm) {
  global $user;
  // Only provide a link if the user has access and the node is a secure note
  // type.
  if (user_access($perm, $user)) {
    $node = node_load($nid);
    if (secure_notes_type_allowed($node->type)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * TODO
 */
function secure_notes_type_allowed($type) {
  $allowed = secure_notes_get_allowed_types(); //variable_get('secure_notes_allowed_types', $default);
  return in_array($type, $allowed);
}

/**
 * TODO
 */
function secure_notes_get_allowed_types() {
  $default = in_array('secure_note', array_keys(node_type_get_names())) ? array('secure_note' => 'secure_note') : array();
  return variable_get('secure_notes_allowed_types', $default);
}

/**
 * Implements hook_node_view().
 */
function secure_notes_node_view($node, $view_mode, $langcode) {
  global $user;
  $allowed = secure_notes_get_allowed_types();
  // Deny normal access to secure notes.
  if (in_array($node->type, $allowed)) {
    if (!user_access('secure notes node view', $user)) {
      if (empty($node->note_pickup)) {
        drupal_access_denied();
      }
    }
  }
}
