<?php

/**
 * @file
 * TODO
 */

/**
 * Implements hook_menu().
 */
function secure_notes_menu() {
  $items = array();
  $items['admin/config/content/secure-notes'] = array(
    'title' => 'Secure Notes Settings',
    'description' => 'Administer Secure Notes Settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('secure_notes_admin_settings_form'),
    'access arguments' => array('manage secure notes settings'),
    'file' => 'secure_notes.admin.inc',
  );
  return $items;
}

/**
 * TODO
 */
function secure_notes_node_access($node, $op, $account) {
  $access = NODE_ACCESS_IGNORE;
  if (isset($_GET['secure-note-token'])) {
    switch ($op) {
      case 'create':
        if (secure_notes_create_token_valid($_GET['secure-note-token'], $node)) {
          $access = NODE_ACCESS_ALLOW;
        }
        break;

      case 'view':
        if (secure_notes_view_token_valid($GET['secure-note-token'], $node->nid)) {
          $access = NODE_ACCESS_ALLOW;
        }
        break;
    }
  }
  return $access;
}

/**
 * TODO
 */
function secure_notes_create_token_valid($token, $node) {
  $allowed_types = variable_get('secure_notes_allowed_types', array());
  // TODO just a stub now.
  if ($node == 'secure_note') {
    return TRUE;
  }
  return FALSE;
}


/**
 * TODO
 */
function secure_notes_view_token_valid($token, $nid) {
  return FALSE;
}
