<?php

/**
 * @file
 *
 * @todo
 */

function secure_notes_autodelete_node_view($node, $view_mode, $langcode) {
  // @todo user hook_forms so that on overview pages we don't have conflicting
  // form ids.
  if (secure_notes_type_enabled($node->type)) {
    $node->content['secure_notes_pickup'] = array(
      'form' => drupal_get_form('secure_notes_autodelete_pickup_confirm_form', $node->nid),
      '#weight' => 10,
    );
  }
}

function secure_notes_autodelete_pickup_confirm_form($form, $form_state, $nid) {
  $nid = 0;

  $form['pickup_nid'] = array(
    '#type' => 'value',
    '#value' => $nid,
  );

  $form['pickup_instructions'] = array(
    '#type' => 'item',
    '#description' => t('Once you have sucessfully retrieved this data, confirm the pickup to mark the node for automatic removal.'),
  );

  $form['pickup_confirm'] = array(
    '#type' => 'submit',
    '#value' => t('Pickup complete'),
  );
  return $form;
}
